App\Entity\Location:
    properties:
        city:
            - NotBlank: { groups: ['create','edit'], message: 'City is required.' }
            - Length:   { groups: ['create','edit'], min: 2, max: 100 }

        country:
            - NotBlank: { groups: ['create','edit'] }
            - Choice:
                  groups: ['create','edit']
                  choices: [PL, DE, FR, ES, IT, GB, US]
                  message: 'Invalid country.'

        latitude:
            - NotNull: { groups: ['create','edit'] }
            - Range:   { groups: ['create','edit'], min: -90,  max: 90 }

        longitude:
            - NotNull: { groups: ['create','edit'] }
            - Range:   { groups: ['create','edit'], min: -180, max: 180 }

App\Entity\Measurement:
    properties:
        date:
            - NotNull: { groups: ['create','edit'] }
        celsius:
            - NotNull: { groups: ['create','edit'] }
            - Range:   { groups: ['create','edit'], min: -80, max: 60 }
        humidity:
            - NotNull: { groups: ['create','edit'] }
            - Range:   { groups: ['create','edit'], min: 0, max: 100 }
        location:
            - NotNull: { groups: ['create','edit'] }
